[project]
name = "skilllens-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.139.0",
    "fastapi-cloud-cli>=0.23.0",
    "greenlet>=3.5.3",
    "httpx>=0.28.1",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.51",
    "strawberry-graphql[fastapi]>=0.322.2",
    "uvicorn[standard]>=0.51.0",
]
