SKILLS_CATALOG: dict[str, tuple[str, list[str]]] = {
    # Languages
    "Python": ("language", [r"python"]),
    "JavaScript": ("language", [r"javascript", r"\bjs\b"]),
    "TypeScript": ("language", [r"typescript", r"\bts\b"]),
    "Java": ("language", [r"\bjava\b(?!script)"]),
    "C#": ("language", [r"\bc#", r"\bc-sharp", r"\bcsharp"]),
    "C++": ("language", [r"\bc\+\+"]),
    "Go": ("language", [r"\bgolang\b", r"\bgo\b(?=\s*(developer|engineer|programming|language))"]),
    "Rust": ("language", [r"\brust\b"]),
    "PHP": ("language", [r"\bphp\b"]),
    "Ruby": ("language", [r"\bruby\b"]),
    "Kotlin": ("language", [r"\bkotlin\b"]),
    "Swift": ("language", [r"\bswift\b"]),
    "SQL": ("language", [r"\bsql\b"]),
    # Frontend
    "React": ("frontend", [r"\breact(\.?js)?\b(?!\s*native)"]),
    "React Native": ("frontend", [r"react\s*native"]),
    "Vue": ("frontend", [r"\bvue(\.?js)?\b"]),
    "Angular": ("frontend", [r"\bangular(js)?\b"]),
    "Next.js": ("frontend", [r"\bnext\.?js\b"]),
    "Tailwind CSS": ("frontend", [r"\btailwind"]),
    "HTML": ("frontend", [r"\bhtml5?\b"]),
    "CSS": ("frontend", [r"\bcss3?\b"]),
    # Backend frameworks
    "Django": ("backend", [r"\bdjango\b"]),
    "FastAPI": ("backend", [r"\bfastapi\b"]),
    "Flask": ("backend", [r"\bflask\b"]),
    "Node.js": ("backend", [r"\bnode\.?js\b", r"\bnodejs\b"]),
    "Express": ("backend", [r"\bexpress\.?js\b"]),
    "Spring": ("backend", [r"\bspring\s*(boot)?\b"]),
    "Ruby on Rails": ("backend", [r"\brails\b", r"ruby\s*on\s*rails"]),
    "Laravel": ("backend", [r"\blaravel\b"]),
    ".NET": ("backend", [r"\b\.net\b", r"\bdotnet\b", r"\basp\.net\b"]),
    "GraphQL": ("backend", [r"\bgraphql\b"]),
    "REST APIs": ("backend", [r"\brest(ful)?\s*(api)?s?\b"]),
    # Databases
    "PostgreSQL": ("database", [r"\bpostgres(ql)?\b"]),
    "MySQL": ("database", [r"\bmysql\b"]),
    "MongoDB": ("database", [r"\bmongo(db)?\b"]),
    "Redis": ("database", [r"\bredis\b"]),
    "Elasticsearch": ("database", [r"\belastic\s*search\b"]),
    # Cloud & DevOps
    "AWS": ("cloud", [r"\baws\b", r"amazon\s*web\s*services"]),
    "Azure": ("cloud", [r"\bazure\b"]),
    "GCP": ("cloud", [r"\bgcp\b", r"google\s*cloud"]),
    "Docker": ("devops", [r"\bdocker\b"]),
    "Kubernetes": ("devops", [r"\bkubernetes\b", r"\bk8s\b"]),
    "Terraform": ("devops", [r"\bterraform\b"]),
    "CI/CD": ("devops", [r"\bci/?cd\b", r"continuous\s*(integration|deployment|delivery)"]),
    "Linux": ("devops", [r"\blinux\b"]),
    "Git": ("tool", [r"\bgit\b(?!hub|lab)"]),
    # Data & AI
    "Pandas": ("data", [r"\bpandas\b"]),
    "NumPy": ("data", [r"\bnumpy\b"]),
    "TensorFlow": ("data", [r"\btensorflow\b"]),
    "PyTorch": ("data", [r"\bpytorch\b"]),
    "Machine Learning": ("data", [r"machine\s*learning", r"\bml\b"]),
    "LLMs": ("data", [r"\bllms?\b", r"large\s*language\s*models?"]),
    # Mobile
    "Flutter": ("mobile", [r"\bflutter\b"]),
    "Android": ("mobile", [r"\bandroid\b"]),
    "iOS": ("mobile", [r"\bios\b"]),
}